# Generated by Django 5.1.7 on 2025-03-15 09:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=32)),
                ('subcategory', models.CharField(max_length=32)),
                ('item_name', models.CharField(max_length=128)),
                ('brand_name', models.CharField(max_length=128)),
                ('generic_name', models.CharField(max_length=128)),
                ('dosage_form', models.CharField(max_length=32)),
                ('strength_per_size', models.CharField(default=None, max_length=32, null=True)),
                ('packaging', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
                ('unit_size', models.CharField(choices=[('ml', 'Milliliters'), ('Each', 'Each'), ('Pack', 'Pack'), ('g', 'Grams'), ('Packs', 'Packs'), ('Rolls', 'Rolls'), ('Tubes', 'Tubes'), ('Bottles', 'Bottles'), ('Bars', 'Bars'), ('Kits', 'Kits'), ('Tablets', 'Tablets'), ('Units', 'Units'), ('Capsules', 'Capsules'), ('Vials', 'Vials'), ('Softgels', 'Softgels'), ('Tablet', 'Tablet')], default='Each', max_length=16)),
                ('date_of_delivery', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('stocks', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.inventoryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
