# Generated by Django 5.1.7 on 2025-03-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='stocks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
