# Generated by Django 5.1.7 on 2025-03-24 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_rename_item_inventorytransaction_item_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='item_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicines.inventorystock'),
        ),
    ]
