# Generated by Django 5.1.7 on 2025-03-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0005_alter_inventorytransaction_item_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystock',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
