# Generated by Django 5.1.7 on 2025-03-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_alter_inventorystock_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventorystock',
            unique_together={('item', 'expiration_date')},
        ),
    ]
