# Generated by Django 5.1.7 on 2025-03-24 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0007_alter_inventorystock_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystock',
            name='date_of_delivery',
            field=models.DateField(default=datetime.datetime(2025, 3, 24, 8, 49, 14, 924548, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='inventorystock',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 24, 8, 49, 14, 924566, tzinfo=datetime.timezone.utc)),
        ),
    ]
