# Generated by Django 5.1.7 on 2025-03-24 08:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0008_alter_inventorystock_date_of_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystock',
            name='date_of_delivery',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventorystock',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
