# Generated by Django 5.1.7 on 2025-03-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0009_alter_inventorystock_date_of_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='packaging',
            field=models.CharField(choices=[('bottle', 'Bottle'), ('blister_pack', 'Blister Pack'), ('box', 'Box'), ('pack', 'Pack'), ('roll', 'Roll'), ('tube', 'Tube'), ('bar', 'Bar'), ('1_box', '1 box'), ('100_per_pack', "100's per pack"), ('1_roll', '1 roll'), ('1_tube', '1 tube'), ('1_bottle', '1 bottle'), ('1_bar', '1 bar'), ('1_kit', '1 kit'), ('20_per_bottle', "20's per bottle"), ('100ml_bottle', '100mL bottle'), ('10_per_blister', "10's per blister"), ('1_unit', '1 unit'), ('6_per_blister', "6's per blister"), ('10ml_vial', '10mL vial'), ('jar', 'Jar'), ('30_per_bottle', "30's per bottle"), ('60_per_bottle', "60's per bottle")], max_length=32),
        ),
    ]
